name: Pre-build Moonstream Portal frontend

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check build
        run: |
          npm i
          npm run build
